### ISSUE TITLE
Bug on concatenated formulas

### ISSUE THREAD

**Issue by madebycambiamentico** [jsegarra1971/MyExcel#36]
the "&" symbol is not escaped correctly (should become "\&amp;") for formulas like

`="test string " & A1 & " with concatenated values"`

for now the only way to solve the problem is to manually escape the value before setting the cell, like so:

`excel.set(0, 0,0, '="test " & A1 & " concatenated"'.replace(/&/ig,"&amp;"))`

If there's an option to give into the `set` function let me know!

**Comment by josesegarra** [comment]
The fix would require to diferentiate when the symbol is used, so that:

`"test string " & A1 & " John & Mary"` would transform into `"test string " &amp; A1 &amp; " John & Mary"`

This would require a implementing a parser for Excel formula notation. 
This is outside the scope of this component, but I am open to contributions.
