### ISSUE TITLE
On excel.generate it remove leading 0 if my string in staring with 0

### ISSUE THREAD

**Issue by Mohit8982** [jsegarra1971/MyExcel#37]
excel.set(0, j, a, e.name);
excel.set(0, j, a, e.bank_name);
excel.set(0, j, a, e.account_no);
excel.set(0, j, a, e.bank_name);

on excel.generate it removes leading 0 from account number starting with zero

**Comment by flowser** [comment]
did you solve it?

**Comment by josesegarra** [comment]
Leading ZEROS are removed in NUMBERS, the FIX is to store the number as a string. 

When generating a cell, if the cell is NOT a NUMBER or has the isString flag then it is generated as a string otherwise as a number. The isString flag can be set in the cell style

So, this should do the trick. 

```
var asString=excel.addStyle ( { isstring:true}); 
excel.set(0, j, a, e.account_no,asString);

```
Let me know how it works...
