### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by amchconsult** [jsegarra1971/MyExcel#40]
how can I change the generate function to just generate all to string without zip function?
I just need to get the xml string

thank you for your help

**Comment by josesegarra** [comment]
An Excel file is not a single XML file, but a set of XML files following a predefined structure. All these files are bundled in the ZIP.  If you are interested in the XML for a specific file, just do not call the ZIP function. For example, in the generate function, instead of:

```
  var zip = new JSZip();                                 // Create a ZIP file
  zip.file('_rels/.rels', sheets.toRels());              // Add WorkBook RELS to the ZIP  
  var xl = zip.folder('xl');                             // Add a XL folder for sheets to the ZIP
  xl.file('workbook.xml', sheets.toWorkBook());          // Add WorkBook.xml to the ZIP
  xl.file('styles.xml', styles.toStyleSheet());          // Add Styles.xml to the ZIP

```
Just remove the ZIP related code:

```
  var reslXML=sheets.toRels();                            // XML text of RELS   
  var sheetsXML=sheets.toWorkBook();             // XML of WorkBook
  var stylesXML=styles.toStyleSheet();               // XML of styles          

```

**Comment by amchconsult** [comment]
thank you
